In [1]:
import pandas as pd
import src.util as util

## Road DDO and reddit datasets

In [8]:
data_path = './data/llm-inference-data/'
data_ddo = pd.read_parquet(data_path + 'df_ddo_hf.parquet')
data_reddit = pd.read_parquet(data_path + 'df_reddit_hf.parquet')

In [9]:
data_ddo.head(2)

,user_name,debate_title,debate_texts,party,party_short,debate_category,context,num_token,short_text,num_token_short,party_out_gpt4o,confidence_gpt4o,party_out_llama8b,confidence_llama8b,clean_text
0,0092678,is french horn better than clarinet in intelle...,[\n \n this is my first debate so i dont exp...,Democratic Party,Democratic,Arts,Debate title: is french horn better than clari...,98,Debate title: is french horn better than clari...,98,Democratic,1.0,Republican,1.0,french horn better clarinet intellectual state...
1,0092678,"what makes wings so amazing (buffalo wings, tr...","[\n \n i dissagree, forfeit, \n \n still d...",Democratic Party,Democratic,Miscellaneous,Debate title: what makes wings so amazing (buf...,50,Debate title: what makes wings so amazing (buf...,50,Republican,1.0,Republican,1.0,makes wings amazing buffalo wings traditional ...

In [10]:
data_reddit.head(2)

,user_name,party_short,subreddit,comment_body,num_tokens,inferred_category,party_out_gpt4o,confidence_gpt4o,party_out_llama8b,confidence_llama8b,clean_text
0,-BrutusBuckeye,Republican,AskAChristian,I believe you're thinking of the NAB Do not be...,314,Religion,Republican,4.0,Republican,1.0,believe thinking nab surprised brothers sister...
1,-BrutusBuckeye,Republican,CFB,"What do you mean? Gus ""Jaguar"" Johnson is my d...",701,Sports,Democratic,1.0,Republican,2.0,mean gus jaguar johnson dude im fine hot take ...

## Calculate text- and user-level inference and compute F1 scores

In [11]:
#example : calculation of text-level, user-level(majority, conf-weighted, max-conf) F1 scores
util.user_level_f1_fourtypes(data_ddo, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')

(0.6465938459097378,
 0.7033612627650411,
 0.7257321380640238,
 0.7237062062741881)

### 1. DDO - GPT-4o

F1 scores based on the inference results of GPT-4o (for Aggregated, Political, and General cases)

In [15]:
def print_three_decimals(values: tuple[float, ...]) -> None:
    formatted = tuple(f"{v:.3f}" for v in values)
    print(formatted)

In [25]:
print("1. Aggregated")
result_ddo_gpt4  = util.user_level_f1_fourtypes(data_ddo, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')
print_three_decimals(result_ddo_gpt4)

print("2. Political")
data_ddo_pol    = data_ddo[data_ddo['debate_category']=='Politics']
result_ddo_pol_gpt4 = util.user_level_f1_fourtypes(data_ddo_pol, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')
print_three_decimals(result_ddo_pol_gpt4)

print("3. General")
data_ddo_nonpol = data_ddo[data_ddo['debate_category']!='Politics']
result_ddo_nonpol_gpt4 = util.user_level_f1_fourtypes(data_ddo_nonpol, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')
print_three_decimals(result_ddo_nonpol_gpt4)

1. Aggregated
('0.647', '0.703', '0.726', '0.724')
2. Political
('0.711', '0.740', '0.754', '0.750')
3. General
('0.619', '0.661', '0.682', '0.685')

### 2. DDO - Llama-3.1-8B

In [26]:
print("1. Aggregated")
result_ddo_llama8b  = util.user_level_f1_fourtypes(data_ddo, prediction_col='party_out_llama8b', confidence_col='confidence_llama8b')
print_three_decimals(result_ddo_llama8b)

print("2. Political")
data_ddo_pol    = data_ddo[data_ddo['debate_category']=='Politics']
result_ddo_pol_llama8b = util.user_level_f1_fourtypes(data_ddo_pol, prediction_col='party_out_llama8b', confidence_col='confidence_llama8b')
print_three_decimals(result_ddo_pol_llama8b)

print("3. General")
data_ddo_nonpol = data_ddo[data_ddo['debate_category']!='Politics']
result_ddo_nonpol_llama8b = util.user_level_f1_fourtypes(data_ddo_nonpol, prediction_col='party_out_llama8b', confidence_col='confidence_llama8b')
print_three_decimals(result_ddo_nonpol_llama8b)

1. Aggregated
('0.619', '0.666', '0.682', '0.695')
2. Political
('0.681', '0.716', '0.725', '0.728')
3. General
('0.595', '0.628', '0.641', '0.647')

### 3. Reddit - GPT-4o

In [27]:
print("1. Aggregated")
result_reddit_gpt4  = util.user_level_f1_fourtypes(data_reddit, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')
print_three_decimals(result_reddit_gpt4)

print("2. Political")
data_reddit_pol    = data_reddit[data_reddit['inferred_category']=='Politics']
result_reddit_pol_gpt4 = util.user_level_f1_fourtypes(data_reddit_pol, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')
print_three_decimals(result_reddit_pol_gpt4)

print("3. General")
data_reddit_nonpol = data_reddit[data_reddit['inferred_category']!='Politics']
result_reddit_nonpol_gpt4 = util.user_level_f1_fourtypes(data_reddit_nonpol, prediction_col='party_out_gpt4o', confidence_col='confidence_gpt4o')
print_three_decimals(result_reddit_nonpol_gpt4)

1. Aggregated
('0.624', '0.727', '0.817', '0.839')
2. Political
('0.777', '0.805', '0.821', '0.829')
3. General
('0.606', '0.683', '0.772', '0.799')

### Reddit - Llama-3.1-8B

In [28]:
print("1. Aggregated")
result_reddit_llama8b  = util.user_level_f1_fourtypes(data_reddit, prediction_col='party_out_llama8b', confidence_col='confidence_llama8b')
print_three_decimals(result_reddit_llama8b)

print("2. Political")
data_reddit_pol    = data_reddit[data_reddit['inferred_category']=='Politics']
result_reddit_pol_llama8b = util.user_level_f1_fourtypes(data_reddit_pol, prediction_col='party_out_llama8b', confidence_col='confidence_llama8b')
print_three_decimals(result_reddit_pol_llama8b)

print("3. General")
data_reddit_nonpol = data_reddit[data_reddit['inferred_category']!='Politics']
result_reddit_nonpol_llama8b = util.user_level_f1_fourtypes(data_reddit_nonpol, prediction_col='party_out_llama8b', confidence_col='confidence_llama8b')
print_three_decimals(result_reddit_nonpol_llama8b)

1. Aggregated
('0.534', '0.527', '0.657', '0.763')
2. Political
('0.670', '0.687', '0.723', '0.729')
3. General
('0.520', '0.508', '0.621', '0.723')

### Combine the results to a single dataframe

In [33]:
combined_result = [
    ["Dataset", "Context", "Text-level F1-score", "User-level F1-score", "User-level F1-score (conf-weighted)", "User-level F1-score(max-conf)"],
    ["Debate.org, GPT-4o", "Aggregated"] + list(result_ddo_gpt4),
    ["Debate.org, GPT-4o", "Political"] + list(result_ddo_pol_gpt4),
    ["Debate.org, GPT-4o", "General"] +list(result_ddo_nonpol_gpt4),
    ["Debate.org, Llama-3.1-8B", "Aggregated"] + list(result_ddo_llama8b),
    ["Debate.org, Llama-3.1-8B", "Political"] + list(result_ddo_pol_llama8b),
    ["Debate.org, Llama-3.1-8B", "General"] + list(result_ddo_nonpol_llama8b),
    ["Reddit, GPT-4o", "Aggregated"] + list(result_reddit_gpt4),
    ["Reddit, GPT-4o", "Political"] + list(result_reddit_pol_gpt4),
    ["Reddit, GPT-4o", "General"] + list(result_reddit_nonpol_gpt4),
    ["Reddit, Llama-3.1-8B", "Aggregated"] + list(result_reddit_llama8b),
    ["Reddit, Llama-3.1-8B", "Political"] + list(result_reddit_pol_llama8b),
    ["Reddit, Llama-3.1-8B", "General"] + list(result_reddit_nonpol_llama8b)
]

df_result = pd.DataFrame(combined_result[1:], columns=combined_result[0])

In [34]:
df_result

,Dataset,Context,Text-level F1-score,User-level F1-score,User-level F1-score (conf-weighted),User-level F1-score(max-conf)
0,"Debate.org, GPT-4o",Aggregated,0.646594,0.703361,0.725732,0.723706
1,"Debate.org, GPT-4o",Political,0.710674,0.739892,0.754039,0.750291
2,"Debate.org, GPT-4o",General,0.619338,0.661394,0.681726,0.684931
3,"Debate.org, Llama-3.1-8B",Aggregated,0.618798,0.665568,0.682119,0.695061
4,"Debate.org, Llama-3.1-8B",Political,0.681048,0.716321,0.725414,0.728212
5,"Debate.org, Llama-3.1-8B",General,0.595056,0.628278,0.640918,0.646849
6,"Reddit, GPT-4o",Aggregated,0.623756,0.727126,0.817279,0.839043
7,"Reddit, GPT-4o",Political,0.776697,0.805464,0.821085,0.829228
8,"Reddit, GPT-4o",General,0.605747,0.683266,0.771702,0.798664
9,"Reddit, Llama-3.1-8B",Aggregated,0.533903,0.526507,0.656585,0.763373
10,"Reddit, Llama-3.1-8B",Political,0.670267,0.686529,0.722899,0.729204
11,"Reddit, Llama-3.1-8B",General,0.520022,0.508063,0.621244,0.722719