In [1]:
import pandas as pd

## Road DDO and reddit datasets

In [4]:
data_path = '../data/llm-inference-data/'
df_ddo = pd.read_parquet(data_path + 'df_ddo_hf.parquet')
df_reddit = pd.read_parquet(data_path + 'df_reddit_hf.parquet')

In [8]:
df_ddo.head(2)

,user_name,debate_title,debate_texts,party,party_short,debate_category,context,num_token,short_text,num_token_short,party_out_gpt4o,confidence_gpt4o,party_out_llama8b,confidence_llama8b,clean_text
0,0092678,is french horn better than clarinet in intelle...,[\n \n this is my first debate so i dont exp...,Democratic Party,Democratic,Arts,Debate title: is french horn better than clari...,98,Debate title: is french horn better than clari...,98,Democratic,1.0,Republican,1.0,french horn better clarinet intellectual state...
1,0092678,"what makes wings so amazing (buffalo wings, tr...","[\n \n i dissagree, forfeit, \n \n still d...",Democratic Party,Democratic,Miscellaneous,Debate title: what makes wings so amazing (buf...,50,Debate title: what makes wings so amazing (buf...,50,Republican,1.0,Republican,1.0,makes wings amazing buffalo wings traditional ...

In [9]:
df_reddit.head(2)

,user_name,party_short,subreddit,comment_body,num_tokens,inferred_category,party_out_gpt4o,confidence_gpt4o,party_out_llama8b,confidence_llama8b,clean_text
0,-BrutusBuckeye,Republican,AskAChristian,I believe you're thinking of the NAB Do not be...,314,Religion,Republican,4.0,Republican,1.0,believe thinking nab surprised brothers sister...
1,-BrutusBuckeye,Republican,CFB,"What do you mean? Gus ""Jaguar"" Johnson is my d...",701,Sports,Democratic,1.0,Republican,2.0,mean gus jaguar johnson dude im fine hot take ...